name: Deploy Frontend
on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Устанавливаем pnpm на сервер GitHub перед установкой Node.js
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # Укажите вашу мажорную версию pnpm, если нужно (например, 8 или 9)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm' # Включаем кеширование для pnpm, чтобы сборка шла быстрее
          cache-dependency-path: 'frontend/pnpm-lock.yaml'

      # 2. Переходим в frontend и ставим зависимости через pnpm
      - name: Install dependencies
        run: |
          cd frontend
          pnpm i --frozen-lockfile

      # 3. Собираем проект
      - name: Build
        run: |
          cd frontend
          pnpm run build

      # 4. Хак для React Router (Vite по умолчанию собирает в frontend/dist)
      - name: SPA Routing Hack (404.html)
        run: cp frontend/dist/index.html frontend/dist/404.html

      # 5. Загружаем артефакт
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "frontend/dist"

      # 6. Публикуем на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
