name: Deploy Frontend
on:
  push:
    branches: [master] # Сработает при пуше в ветку master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Стабильная LTS-версия (24 еще не вышла/не поддерживается стабильно)

      # Переходим в папку frontend и ставим зависимости
      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      # Собираем проект (Vite создает папку dist внутри frontend)
      - name: Build
        run: |
          cd frontend
          npm run build

      # ХАК ДЛЯ REACT ROUTER: Исправлен путь, копируем index.html в той же папке dist
      - name: SPA Routing Hack (404.html)
        run: cp frontend/dist/index.html frontend/dist/404.html

      # Загружаем собранную папку dist из папки frontend
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "frontend/dist"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
